@startuml

!theme plain
left to right direction
skinparam linetype ortho

class Action
class Actuator
class ActuatorAction {
  - value: SIGNAL
  - actuator: Actuator
}
class App {
  - initial: State
  - states: List<State>
  - bricks: List<Brick>
  - name: String
}
class Brick {
  - name: String
  - pin: int
}
enum LogicalOperator << enumeration >> {
  + NONE: 
  + OR: 
  - operator: String
  + AND: 
}
interface NamedElement << interface >>
class Pin {
  - name: String
  - number: String
  - pinType: PinType
}
enum PinType << enumeration >> {
  - title: String
  + DIGITAL_OUTPUT: 
  + ANALOG_INPUT: 
  + ANALOG_OUTPUT: 
  + DIGITAL_INPUT: 
}
enum SIGNAL << enumeration >> {
  + HIGH: 
  + LOW: 
}
class Screen {
  - rowLength: Integer
  - busPins: List<Integer>
  - lineLength: Integer
}
class ScreenAction {
  - screen: Screen
  - content: String
}
class Sensor
class State {
  - name: String
  - actions: List<Action>
  - transition: Transition
}
class ToWiring {
  - bounceGardName: String
}
class Transition {
  - transitionConditions: List<TransitionCondition>
  - next: State
  - transitionFirst: TransitionFirst
}
class TransitionCondition {
  - value: SIGNAL
  - sensor: Sensor
  - logicalOperator: LogicalOperator
}
class TransitionFirst {
  - sensor: Sensor
  - value: SIGNAL
}
interface Visitable << interface >>
class Visitor<T> {
  # result: T
  # context: Map<String, Object>
}

Action               -[#008200,dashed]-^  Visitable           
Actuator             -[#000082,plain]-^  Brick               
ActuatorAction       -[#000082,plain]-^  Action              
ActuatorAction      "1" *-[#595959,plain]-> "actuator\n1" Actuator            
ActuatorAction      "1" *-[#595959,plain]-> "value\n1" SIGNAL              
App                 "1" *-[#595959,plain]-> "bricks\n*" Brick               
App                  -[#008200,dashed]-^  NamedElement        
App                 "1" *-[#595959,plain]-> "states\n*" State               
App                  -[#008200,dashed]-^  Visitable           
Brick                -[#008200,dashed]-^  NamedElement        
Brick                -[#008200,dashed]-^  Visitable           
Pin                  -[#008200,dashed]-^  NamedElement        
Pin                 "1" *-[#595959,plain]-> "pinType\n1" PinType             
Screen               -[#000082,plain]-^  Brick               
ScreenAction         -[#000082,plain]-^  Action              
ScreenAction        "1" *-[#595959,plain]-> "screen\n1" Screen              
Sensor               -[#000082,plain]-^  Brick               
State               "1" *-[#595959,plain]-> "actions\n*" Action              
State                -[#008200,dashed]-^  NamedElement        
State               "1" *-[#595959,plain]-> "transition\n1" Transition          
State                -[#008200,dashed]-^  Visitable           
ToWiring             -[#000082,plain]-^  Visitor             
Transition          "1" *-[#595959,plain]-> "next\n1" State               
Transition          "1" *-[#595959,plain]-> "transitionConditions\n*" TransitionCondition 
Transition          "1" *-[#595959,plain]-> "transitionFirst\n1" TransitionFirst     
Transition           -[#008200,dashed]-^  Visitable           
TransitionCondition "1" *-[#595959,plain]-> "logicalOperator\n1" LogicalOperator     
TransitionCondition "1" *-[#595959,plain]-> "value\n1" SIGNAL              
TransitionCondition "1" *-[#595959,plain]-> "sensor\n1" Sensor              
TransitionFirst     "1" *-[#595959,plain]-> "value\n1" SIGNAL              
TransitionFirst     "1" *-[#595959,plain]-> "sensor\n1" Sensor              
@enduml
